// This file is generated by ./bin/translations.
//
// It contains translations that appear before the user has logged in and
// fetched userInterfaceText from /my_data. This is bundled into the app.

const preLoginTranslations = {
  "fr": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "par ex. 0123456789"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Erreur réseau"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Chargement..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Quel est ton numéro de téléphone?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Détails de l'erreur:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Erreur inattendue"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Désolé, il semble y avoir un problème avec nos ordinateurs. Veuillez réessayer plus tard."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Désolé, il semble y avoir un problème. Si cela continue, essayez de réinstaller l'application."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Problème: le numéro de téléphone n'est pas reconnu."
    }
  ],
  "hi": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "e.g. 8894366114"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "नेटवर्क त्रुटि"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "लोड हो रहा है..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "आपका मोबाइल नंबर क्या है?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "गलतियों की जानकारी"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "अनपेक्षित समस्या"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "क्षमा करें, ऐसा लगता है कि हमारे कंप्यूटर में कोई समस्या है। कुछ समय बाद पुन: प्रयास करें।"
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "क्षमा करें, लगता है कि कोई समस्या हुई है। अगर ऐसा होता रहता है, तो ऐप को फिर से इंस्टॉल करके देखें।"
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "लॉगिन विफल। अज्ञात मोबाइल नंबर।"
    }
  ],
  "laj": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Apor me nama cim 0716787679"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Peko me netwak"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Kur tye ayikere"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Nama cimi tye adi?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Anyut me jami mogo orocere:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Gin orocere ame timere ape iyikere iye"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Timwa kica, peko moro tye I Kompiuta wa ni. Kong dok item  imede itemo."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Tim kica, ginoro tye orocere. Ka omede kede timere bed temo me cako keto puruguram."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Nama cim pe odonyo. Nama cim pe tye angeye."
    }
  ],
  "ro": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "ex. 0700000000"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Eroare de rețea"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Se încarcă"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Care este numărul tău de telefon?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Detalii despre eroare:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Eroare neașteptată"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Ne pare rău, se pare că există o problemă cu calculatoarele noastre. Vă rugăm să încercați din nou mai târziu."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Ne pare rău, se pare că există o problemă. Dacă continuă să se întâmple, încercați să reinstalați aplicația."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Autentificare esuata. Număr mobil necunoscut."
    }
  ],
  "es": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "e.g. 77774444"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Error de red"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Cargando..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "¿Cual es tu numero de telefono?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Error de detalles:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Error inesperado"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Lo sentimos, parece haber un problema con nuestras computadoras. Por favor, inténtelo de nuevo más tarde."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Lo siento, parece que hay un problema. Si sigue sucediendo, intente reinstalar la aplicación."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Error de inicio de sesion. Número de móvil no reconocido."
    }
  ],
  "ta": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "உ-ம்  0712345678"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "வலையமைப்புத்தவறு"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "ஏற்றம்..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "உங்கள் கைபேசி இலக்கம் என்ன?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "பிழை விபரங்கள்"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "எதிர்பாரத தவறு"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "மன்னிக்கவும், எங்கள் கணிணிகளில் தவறு இருப்பதாகத் தெரிகிறது. தயவு செய்து சிறிது நேரத்தின் பின்னர் முயற்சி செய்யவும்."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "மன்னிக்கவும், ஒரு  சிக்கல் இருப்பதாகத் தெரிகிறது.இவ்வாறு தொடர்ந்தால் செயலியை மீள றிறுவ முயற்சி செய்யவும்."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "உள்நுழைவு தோல்வி, அங்கீகரிக்கப்படாத கைபேசி இலக்கம்."
    }
  ],
  "rw": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Urugero: 07123456678"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Akabazo kuri rezo"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Biracyaza…"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Nimero ya telefoni ukoresha ni iyihe?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Akabazo kadasanzwe:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Akabazo katitezwe"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Ihanga, hashobora kuba hari ikibazo muri mudasobwa zacu. Nyabuneka, ongera ugerageze."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Ihangane, birashoboka ko hari ikibazo. Nibikomeza, gerageza wongere ushyiremo iyi apu."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Kwinjira byanze. Nimero ya terefoni itazwi"
    }
  ],
  "en": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "e.g. 0123456789"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Network error"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Loading..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "What’s your mobile number?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Error details:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Unexpected error"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Sorry, there seems to be a problem with our computers. Please try again later."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Sorry, there seems to be a problem. If it keeps happening, try reinstalling the app."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Login failed. Unrecognised mobile number."
    }
  ],
  "tet": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "e.g. 0123456789"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Rede faila/Rede ladun di'ak"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Prosesu hela…"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Ita Bo'ot nia numeru telefone hira?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Erru detallu:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": " la espera Erru"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Deskulpa, hare'e ba sei iha probema ho ita nia komputadores. Favor koko fila fali."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Deskulpa,hare'e ba sei iha problema. Bainhira ida ne'e sei akontese, koko reinstala app."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Prosesu faila. Numeru Telefone lalos."
    }
  ],
  "mg": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Oh: 0123456789"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Misy olana ny tambazotram-pifandraisana"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Andalam-pamitana"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Inona ny laharana finday anao?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Pitsopitsony amin'ny fahadisoana:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Fahadisoana tsy nampoizina"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Mialatsiny, ohatran'ny misy olana ny solosaina. Avereno afaka fotoana fohy"
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Mialatsiny, ohatran'ny misy olana. Raha mbola mitohy dia avereno ampidirina ilay rindrambaiko."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Tsy nahomby ny fidirana. Misy diso ny laharana finday."
    }
  ],
  "pt": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Por exemplo: 0123456789"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Erro de rede"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Carregando..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Qual é o número do seu celular?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Detalhes do erro:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Erro inesperado"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Desculpe, parece que há um problema com nossos computadores. Por favor, tente novamente mais tarde."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Desculpe, parece que há um problema. Se continuar acontecendo, tente reinstalar o aplicativo."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Falha no login. Número de celular desconhecido"
    }
  ],
  "am": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "ምሳሌ 0712345678"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "የኔትዎርክ ስህተት"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "እየጫነ"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "የእርስዎ ስልክ ቁጥር ስንት ነው"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "የስህተት ዝርዝር"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "የማይጠበቅ ስህተት"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "ይቅርታ በእኛ ኮምፕዩተር ላይ ችግር ያለ ይመስላል፡፡ እባክዎትን ትንሽ ቆይተው ይሞክሩ"
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "ይቅርታ፣ ችግር ያለ ይመስላል፡፡ ችግሩም ከቀጠለ አፕሊኬሽኑን እንደገና ለማስነሳት ይሞክሩ"
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "የመግባት ተግባር አልተሳካም፡፡ የማይታወቅ ስልክ ቁጥር"
    }
  ],
  "sw": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "Mfano. 0123456789"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Tatizo la mtandao"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Inapakia ..."
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Nambari yako ya simu ni ipi?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "Maelezo ya itilafu:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "itilafu lisilotarajiwa"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Samahani, inaonekana kuna itilafu na kompyuta zetu. Tafadhali jaribu tena baadae."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Samahani, inaonekana kuna itilafu. Ikiendelea kutokea, jaribu kupakua tena programu."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Imeshindikana kuingia. Nambari ya simu aiyasajiliwa kwenye mfumo"
    }
  ],
  "id": [
    {
      "id": 3,
      "key": "login.placeholder",
      "value": "contoh: 081234567890"
    },
    {
      "id": 39,
      "key": "error.network.title",
      "value": "Terjadi kesalahan jaringan"
    },
    {
      "id": 34,
      "key": "loading",
      "value": "Memuat"
    },
    {
      "id": 1,
      "key": "login.prompt",
      "value": "Berapa nomor ponsel Anda?"
    },
    {
      "id": 43,
      "key": "error.details",
      "value": "rincian kesalahan:"
    },
    {
      "id": 41,
      "key": "error.unknown.title",
      "value": "Kesalahan yang tidak terduga"
    },
    {
      "id": 40,
      "key": "error.network.body",
      "value": "Maaf, sepertinya ada masalah dengan komputer kami. Silakan coba lagi nanti."
    },
    {
      "id": 42,
      "key": "error.unknown.body",
      "value": "Maaf, nampaknya ada kesalahan. Jika terus terjadi, coba instal ulang aplikasi."
    },
    {
      "id": 2,
      "key": "login.failed",
      "value": "Gagal masuk. \nNomor ponsel tidak dikenali"
    }
  ]
};

export default preLoginTranslations;
